### ISSUE TITLE
eBookmark dropping tree file structure when in use

### ISSUE THREAD

**Issue by cmccullough2** [cmv/cmv-wab-widgets#11]
I was having trouble with the eBookmark widget you were using in your code.  The folder options disappeared when I used the widget.  I upgraded the widget to the 2.1 version.  It appears to be working correctly now.  https://geonet.esri.com/docs/DOC-6889.  I will continue to test on and off my work network.

**Comment by tmcgee** [comment]
Thanks for letting me know. I don't track the individual custom WAB widgets to see if there have been any breaking changes in new releases of WAB. That's not interesting to me. 😜

**Comment by cmccullough2** [comment]
I get it.  There is way too much out there for QA/QC.  That is why we need to work as a team even though we do not 'work' with each other.

**Comment by cmccullough2** [comment]
I ended up still having the problem with the new version.  When I find a solution, I will share my results.

**Comment by cmccullough2** [comment]
The eBookmark needs to be open: true, and it cannot use placeAt: 'right'.  It appears to work when these values are set.
