### ISSUE TITLE
Bypassing Portal

### ISSUE THREAD

**Issue by ezequias** [cmv/cmv-wab-widgets#13]
Hello

Would be nice if the CMV-wab-widgets could be able to bypass ArcGIS Portal to make it more open to connect to REST map services (like ArcGIS,MapServer and Geoserver).

Sincerely
Ezequias

**Comment by tmcgee** [comment]
@ezequias The implementation of WAB widgets in CMV do not require the use of ArcGIS Portal or ArcGIS On-line. They use the REST services. There may be custom WAB widgets that do have a dependency on portal that I am have not come across.
