### ISSUE TITLE
config/nls folder not in cmv-wab-widgets folder

### ISSUE THREAD

**Issue by cmccullough2** [cmv/cmv-wab-widgets#14]
In the cmv-widgets application there is a config/nls folder.  I am assuming there will be a conflict with the cmv-wab-widgets application.  Is this true?

**Comment by tmcgee** [comment]
No conflict that I am aware of. The `nls` folder under the config folder is completely optional. It is only referenced by configuration files in the demo's config folder for demonstrating the use of multiple languages.

If your configs do not reference the folder, it will not be used and can be excluded completely.  The WAB demo configuration files s in this repo do not use it.
