### ISSUE TITLE
Errors loading custom basemaps when integrating a WAB widget

### ISSUE THREAD

**Issue by JhopStl** [cmv/cmv-wab-widgets#15]
When adding the WAB widgets and their dependencies (_WABMixin in the controller), I get the following errors upon loading a custom basemap:

**Basemap.js:4 esri.dijit.Basemap: unable to find the 'layers' property in parameters
BasemapLayer.js:4 esri.dijit.BasemapLayer: unable to find the 'url' or 'type' property in parameters**  

I was not able to replicate this issue when loading AGOL basemaps.  Also, it's worth noting that the basemap will not load at all in IE when using the same custom basemaps (still loads fine in Chrome, Firefox and Edge). The errors are generated after basemap creation takes place in the config (i.e. wab-measure.js) file.

Any ideas on what could be causing the issue? 
 I've made the test site public: http://map.sccmo.org/Main/cmv_wab/demo.html but I can attach code if needed.

Besides that, the WAB widgets are working great CMV!

Thanks,

Jesse

**Comment by JhopStl** [comment]
Note: Reverting back to WAB versions 2.3 or 2.2 seems allows IE to load the basemap properly, however the aforementioned errors still persist.

**Comment by tmcgee** [comment]
@JhopStl i am using custom basemaps anf WAB version 2.4 without issue. Not sure what the issue is here. I'll try to debug your public app when at a desktop. Thanks for providing that.

**Comment by JhopStl** [comment]
@tmcgee I appreciate it. With that, I've probably just configured something incorrectly...I spent quite awhile looking at it, and I plan on spending even more time when I'm free.

**Comment by tmcgee** [comment]
@JhopStl Since you are using ESRI Map Services, did you try using `basemap` and `baseMapLayers` instead of `layers`? Here's an example for one of your custom basemaps:

``` javascript
aerial2015: {
    title: '2015 Aerial',
    basemap: {
        baseMapLayers: [
            {
                url: 'http://10.10.143.115/scc_gis/rest/services/appservices/JS_ortho2015/MapServer'             
	    }
        ]			
    }
},
```

NOTE: I cannot test using the public application you provided since the i.p. address 10.10.143.115 is not accessible outside your network. I did test using [these basemaps]((https://github.com/cmv/cmv-app/blob/develop/viewer/js/config/basemaps.js#L48-L67)) in the cmv demo.

**Comment by JhopStl** [comment]
@tmcgee Here is the working public URL: http://map.sccmo.org/Main/gis_dev/
I tried your suggestion, and it worked.

Viewer.js
![1](https://cloud.githubusercontent.com/assets/16945459/25629747/417baf14-2f30-11e7-9ff2-e2480aaae005.PNG)

Thanks!

**Comment by cmccullough2** [comment]
Can you use Google Terrain as the main basemap? 
	googleTerrain: {
                title: 'Google Terrain',
                basemap: new Basemap({
                    id: 'googleTerrain',
                    layers: [new BasemapLayer({
                        url: "https://mt${subDomain}.google.com/vt/lyrs=t,r&hl=en&gl=en&x=${col}&y=${row}&z=${level}&s=png",
                        copyright: "Google, 2015",
                        id: "googleTerrain",
                        subDomains: ["0", "1", "2", "3"],
                        type:"WebTiledLayer"
                        })
                    ]
                })
						}
