### ISSUE TITLE
Does "mapClickMode" work with the Enhanced Measure Widget?

### ISSUE THREAD

**Issue by JhopStl** [cmv/cmv-wab-widgets#16]
Is the mapClickMode property intended to work with integrated WAB widgets?  I am having an issue where using Enhanced Measure (measuring with poly line to be specific) clicks on a layer and identifies it.  I've attempted to integrate the mapClickmode functionality, but no luck yet.

http://map.sccmo.org/Main/cmv_wab/demo.html

![enhanceddrawmeasurewab](https://cloud.githubusercontent.com/assets/16945459/25151341/d9020f22-244a-11e7-97da-f766e28d89a1.PNG)

Thanks for looking into this.

**Comment by tmcgee** [comment]
@JhopStl  i think I know what's going on here and it is something I fixed locally. I am on mobile at the moment. I will look at it tomorrow.

**Comment by tmcgee** [comment]
@JhopStl This [commit](https://github.com/cmv/cmv-wab-widgets/commit/0a858ef21d2e9e89e226a3e7c48ea3630014929d#diff-1d4c1328a3d1402f5d5663aab9e563a7) should fix your issue. As I mentioned, this is a fix I have made locally. I'm not sure if I completely missed committing this to the repo in the past or if it was lost in the recent update for the release version of CMV 2.0.0-beta.1.

**Comment by JhopStl** [comment]
@tmcgee That did the trick, thank you!
