### ISSUE TITLE
CheckBox issue in this CMV-WAB viewer

### ISSUE THREAD

**Issue by ERS-Long** [cmv/cmv-wab-widgets#2]
Hi, @tmcgee : Just found out this issue when i tried to add @roemhildtg AppSettings widget to it. Somehow the checkbox is not clickable anymore. I think it is CSS conflicts somewhere, but i could not figure it out. If you check the default print widget, click the setting button, all other controls are fine, but the check box is not clickable. 

here is the print widget
![image](https://cloud.githubusercontent.com/assets/5911272/17338970/56e4a782-58af-11e6-9ae9-d3c49e150c34.png)

here is the appsetting widget
![image](https://cloud.githubusercontent.com/assets/5911272/17339009/7f35a498-58af-11e6-8bd7-826d6b1b8c0c.png)

Please let me know if you have the fix or something.

Thanks a lot!

**Comment by tmcgee** [comment]
This is something that appears to have been fixed in subsequent WAB versions. @ERS-Long If this is still an issue for you using the latest version of WAB (2.4), please let me know. Otherwise, we can close this issue.

**Comment by ERS-Long** [comment]
I will test it this week. Yes, we can close it.
