### ISSUE TITLE
Query WAB widget PopUp - Multiple Field

### ISSUE THREAD

**Issue by mayur9785** [cmv/cmv-wab-widgets#20]
Hi,

I added multiple field for popup configuration in WAB Query widgets options, but it is displaying single field

![cap2](https://user-images.githubusercontent.com/6058868/29363240-df5121fa-8297-11e7-8a05-834a19040965.PNG)

![2](https://user-images.githubusercontent.com/6058868/29363232-dc7c9cde-8297-11e7-965b-3a5dd36783e8.PNG)

**Comment by tmcgee** [comment]
Sorry @mayur9785, I am not familiar with how to configure the Query WAB widget (and most other WAB widgets).
