### ISSUE TITLE
WAB Widgets Content Height

### ISSUE THREAD

**Issue by mayur9785** [cmv/cmv-wab-widgets#21]
Hi,

How do I increase the height of the container so that widget's complete UI we can see without scrolling, as current height is not enough to see the complete UI.

Also, How do I set max-height & min-height for widgets ?

![4](https://user-images.githubusercontent.com/6058868/29364327-b41bd922-829b-11e7-9580-8ddf077f84ba.PNG)

**Comment by tmcgee** [comment]
css for WAB widgets will be specific to that widget. Using Chrome Dev Tools, I inspected that element and it appears you should use the css class `jimu-widget-query`. The style.css for that widget has a `min-height: 237px` for that element. Perhaps something like:

``` css
.jimu-widget-query {
    min-height: 300px !important;
}
```

**Comment by mayur9785** [comment]
@tmcgee Thank You very much 👍 got it.
