### ISSUE TITLE
Chart widget - Enlarge Window

### ISSUE THREAD

**Issue by mayur9785** [cmv/cmv-wab-widgets#23]
HI,

When I click on Enlarge button of Chart widget, the pop up window going out of screen, X & Y axis data and close button not visible on screen.

I would like to set the settings same as Identify popup window as it is display properly on center of the screen even when you maximize the popup.

![9](https://user-images.githubusercontent.com/6058868/29411432-7355644a-835d-11e7-978b-000af8fe9a1f.PNG)

Please suggest me on this.

**Comment by mayur9785** [comment]
@tmcgee I would like to add percentage suffix to each item of pie chart label.

I tried look into Chart.js and Statisticschart.js file but did not get.

Could you please suggest me on this where should I add this ?

**Comment by tmcgee** [comment]
@mayur9785 Sorry I was unable to look into this at the time. If you were able to get the Chart widget working for your needs, please close this issue.
