### ISSUE TITLE
Logo for 'sub-configuration' viewers. 

### ISSUE THREAD

**Issue by cmccullough2** [cmv/cmv-wab-widgets#24]
How do I display a different logo in the title section of a 'sub-configuration'?
titles: {
            header: 'Aloha Threat Zone Widget Preview',
            subHeader: 'This is an example of using Web App Builder widgets with CMV',
            pageTitle: 'Aloha Threat Zone Widget Preview'
},

**Comment by cmccullough2** [comment]
I tried this with no luck. 
 titles: {
            header: 'CMV WAB Widgets Test',
            subHeader: 'This is an example of using Web App Builder widgets with CMV',
            pageTitle: 'CMV WAB Widgets Test',
            logo: true,
            path: './cmv/images/Knight_Final_40x40.png'
},

**Comment by tmcgee** [comment]
This is a good possible addition for cmv-app. Closing the issue here since this is unrelated to cmv-wab-widgets.
