### ISSUE TITLE
WAB Widget: Image Discovery

### ISSUE THREAD

**Issue by lolob** [cmv/cmv-wab-widgets#27]
WAB version:  2.4
JS Arcgis version: 3.2
CMV version: 2.0 beta 1.0

Hi,
I need help to use this WAB [Image Discovery](https://github.com/Esri/defense-solutions-proofs-of-concept/tree/master/widgets/ImageDiscovery) runs inside CMV . Install okay show in the picture. However no action on clicking the search tools. I use localhost mosaic datasets as image services. Also, console from the Chrome developer tools shows no errors. Please help. Thanks.

![imagedis](https://user-images.githubusercontent.com/15963902/36768869-2358eb52-1c7c-11e8-9344-b965195e405d.png)

**Comment by tmcgee** [comment]
@lolob I have not used that widget so not sure what the issue might be. Here are a couple of thoughts.

- Might be a configuration issue for the widget. Can you configure/test the widget with your dataset using the WAB Developer Edition (preferably version 2.7).
- Perhaps it is a problem with cmv-wab-widget not supporting something in the older WAB version (2.4)? The current version of cmv-wab-widgets support WAB 2.6 and 2.7 (I expect 2.8 to be out soon).
