### ISSUE TITLE
Wab widgets won’t load

### ISSUE THREAD

**Issue by JMaps88** [cmv/cmv-wab-widgets#29]
Hi,

I’m having trouble getting any wab widgets to load in CMV (I am using the latest version). They appear in the title pane but when  I open them they just stay with the loading dots and never open. I am getting no errors appear anywhere, they just never load. I have tried multiple widgets in the wab repo and it’s the same with all of them. I have a feeling it maybe related to the wabapp-config.js. Was I meant to edit the itemid and portalUrl if my system is completely offline/stand-alone?

Any help you could provide would be hugely appreciated

**Comment by tmcgee** [comment]
@JMaps88 Does the demo code in this repo work for you without changing any code/config? I'd start there then add your layers, then any additional WAB widgets.

**Comment by JMaps88** [comment]
All standard cmv widgets still work fine. I’ll try the demo code when I go into work and let you know. Cheers

**Comment by JMaps88** [comment]
So I got it working on a test version that is available to the internet, however I still can not configure it work offline/stand-alone. Can you confirm that the wab repo can be configured to work offline that same regular CMV widgets can be? The only difference I can see is the wab repo demo references js api 3.24 where as our version is 3.21 hosted locally

**Comment by tmcgee** [comment]
I have used the WAB widgets within CMV with a locally installed version of the JS API. There may be specific requirements for a specific version of WAB requiring a specific version of the JS API. This [table](https://developers.arcgis.com/web-appbuilder/guide/about-versions.htm) shows the corresponding versions. I do not know if those are hard and fast requirements or merely guidelines.

**Comment by JMaps88** [comment]
So there’s no requirement to change the wabapp-config.js to reference a local map or change the portal URL? (Not that I’m using portal)

**Comment by JMaps88** [comment]
Could the problem be that we are using Arc Server 10.2.2 and if so is there a way to solve the issue without updated to a newer version?

**Comment by tmcgee** [comment]
I am not aware of any requirement to change anything in wabapp-config.js.  No portal is required. The existing portalURL is there to follow WAB standards but to my knowledge is not required at all. I commented out the itemID and portalURL and everything still worked. My test did not reference a local copy of the JS API but would not expect that to matter at all.

The older version of ArcGIS Server _could_ be a problem. You can see if the chart that the first version of WAB was released supporting 10.3. As is often the case, there were many changes from 10.2.x to 10.3.x.

You've not mentioned which version of WAB are you using. Please provide that. This repo is using version 2.8. Version 2.9 of WAB has been released but is untested.

Also, what version of CMV are you using? The code in this repo uses the most recent CMV release [v2.0.0-beta.2](https://github.com/cmv/cmv-app/releases/tag/v2.0.0-beta.2) and has not been tested with the current `develop` branch.

**Comment by JMaps88** [comment]
I have tested it with all three versions of WAB provided in the repo (2.6, 2.7 and 2.8) with no difference seen between the three. I am also using the most recent cmv release 2.0.0-beta2. It’s looking more and more likely that my problem stems from WAB not playing working with server 10.2.2. I will have to move away from using WAB widgets and find a way to use just CMV based widgets

**Comment by GilbertLasnier** [comment]
WAB work with 10.02

**Comment by tmcgee** [comment]
@GilbertLasnier According to the chart I linked to above, versions less than 10.3 are not supported by Esri.
