### ISSUE TITLE
The Draw tools in the demo is not charging, I want to try that one if we have a save for the Draft?

### ISSUE THREAD

**Issue by GilbertLasnier** [cmv/cmv-wab-widgets#31]
![image](https://user-images.githubusercontent.com/6784515/48788108-1ed1be80-ecb8-11e8-8344-22f1dfbd7155.png)

**Comment by tmcgee** [comment]
@GilbertLasnier It appears to be working for me:

![image](https://user-images.githubusercontent.com/200780/48793131-deb80f00-ecaa-11e8-88f8-c031924d2449.png)

**Comment by GilbertLasnier** [comment]
Good I try again

**Comment by GilbertLasnier** [comment]
Still doesn't work give me your link...

**Comment by GilbertLasnier** [comment]
Thanks I am an expert to clear the cache...
By the way, i know its not your domain but I have two computers at my home and I am not able to open web scene...use  webgl and graphic card intensive, I work like a crazy man 3 hrs to active the 3d in each browser and I update the graphic card... and still nothing work and the test of web gl work.
I think i must by new computer or new graphic card?
