### ISSUE TITLE
Try to reload my drawing?

### ISSUE THREAD

**Issue by GilbertLasnier** [cmv/cmv-wab-widgets#32]
Sorry I don’t see that one: Wab widgets won’t load 
Your tool Tim is very power full, I try and its work perfectly until i try to reload my drawing?
i make a draw and I save and I reload but I don’t understood something
to reload the draw, cmvSessions.json I have no draw???
![image](https://user-images.githubusercontent.com/6784515/48789299-b7693e00-ecba-11e8-8121-ffa9abc23f2d.png)

I am sure its not a versioning problem
I work with WAB since a while with 10.02 and almost everything work but no dropdown in a popup...

**Comment by tmcgee** [comment]
Sorry but I don't provide support custom WAB widgets. You may want to try with a newer version of the widget(s) and possibly contact their authors. Links are in the README of this repository.

**Comment by GilbertLasnier** [comment]
Ok thanks Tim
